Patch

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,9 +7,14 @@ on:
 jobs:
   BuildSecrets:
     runs-on: ubuntu-latest
-    environment: database
     steps:
       - uses: actions/checkout@v6
+      - name: Check for ENV_FILE secret
+        run: |
+          if [ -z "${{ secrets.ENV_FILE }}" ]; then
+            echo "Error: ENV_FILE secret is not set."
+            exit 1
+          fi
       - name: Create .env file
         run: |
           echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
@@ -34,7 +39,6 @@ jobs:
   build:
     needs: BuildSecrets
     runs-on: ubuntu-latest
-    environment: database
     steps:
       - uses: actions/checkout@v6
       - name : Setup .NET
